apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  credentials: QUtJQVE3T1RMWEtKSDIzV0dYNVc=


#aws_secret_access_key=T0tJTnlBYWtVckMzanRnNzVKSC91VUxRbEhBQXhEenlhNStoQU4rNw==
#ws_access_key_id=QUtJQVE3T1RMWEtKSDIzV0dYNVc=