apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      app: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: rebeccandiwa/udagram-api-feed:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: 1100Mi
          requests:
            cpu: 100m
            memory: 100Mi